environment:
  matrix:
    - nodejs_version: "12"
    - nodejs_version: "10"
    - nodejs_version: "8"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

build: off
shallow_clone: true

before_test:
  - node --version
  - npm --version

test_script:
  - npm test

cache:
  - '%APPDATA%\npm-cache'
